Fix: Fixed some warning in PHP8.
brainstormforce/custom-fonts pull request #38
Opened 2020-12-11 11:31 UTC by shubhw12

PHP Deprecated:  Required parameter $description follows optional parameter $value in C:\laragon\www\phptesting\wp-content\plugins\custom-fonts\includes\class-bsf-custom-fonts-admin.php on line 280

PHP Deprecated:  Required parameter $description follows optional parameter $value in C:\laragon\www\phptesting\wp-content\plugins\custom-fonts\includes\class-bsf-custom-fonts-admin.php on line 280

2020-12-17 11:10 UTC, imnavanath approved these changes

2020-12-18 04:45 UTC, premanshup requested changes

2020-12-18 04:45 UTC, premanshup commented on .github/workflows/phpcs.yml
> +        run: vendor/bin/phpcs
@shubhw12 We have done same changes in this PR as well, can you please check? - https://github.com/brainstormforce/custom-fonts/pull/40/files - Can we close this then?

2020-12-18 04:53 UTC, premanshup requested changes

2020-12-18 04:53 UTC, premanshup commented on README.md
> +- Improvement: PHP8 compatibility.
@shubhw12 Please run `grunt readme` once.

2021-01-14 06:27 UTC, premanshup approved these changes

2021-01-14 06:28 UTC, merged